<?php

require_once 'application/core/SController.php';

class SMainController extends SController
{
    function indexAction()
    {
        //parent::indexAction(); // TODO: Change the autogenerated stub

        //echo 'cnd';

        $this->view->generate('SMainView.php', 'SCommonMarkupView.php');
    }
}