<?php

require_once '../admin/application/core/Controller.php';

class MainController extends Controller
{
    function indexAction()
    {
        //parent::indexAction(); // TODO: Change the autogenerated stub

        //echo 'cnd';

        $this->view->generate('MainView.php', 'CommonMarkupView.php');
    }
}