<?php

require_once '../admin/application/core/Controller.php';

class MainController extends Controller
{
    function indexAction()
    {
        //parent::indexAction(); // TODO: Change the autogenerated stub

        //echo 'cnd';

        //$this->view->generate('MainView.php', 'CommonMarkupView.php');

        $category = 0;

        $items = (new DatabaseHandler())->getItemsByCategory($category);
        $data = new stdClass();
        $data->items = $items;
        $data->category = $category;
        $this->view->generate('WaresView.php', 'CommonMarkupView.php', $data);
    }

    function newAction()
    {
        //parent::indexAction(); // TODO: Change the autogenerated stub

        //echo 'cnd';

        //$this->view->generate('MainView.php', 'CommonMarkupView.php');

        $category = 0;

        $items = (new DatabaseHandler())->getItemsByCategory($category);
        $data = new stdClass();
        $data->items = $items;
        $data->category = $category;
        $this->view->generate('WaresView.php', 'CommonMarkupView.php', $data);
    }
}